<section class="provision_box">
<form class="provision_bg">
    <fieldset class="provision_wrap">
        <h2 class="provision_txt">PROVISION <br>&<br> SPARE/STORE</h2>
        <div class="txt_wrap">
            <div class="location">
                <select name="" id="location_box">
                    <option>지역선택</option>
                    <option>국내</option>
                    <option>미주서안</option>
                    <option>미주동안</option>
                    <option>아시아</option>
                    <option>아프리카,중동</option>
                    <option>유럽</option>
                    <option>중남미</option>
                    <option>호주,뉴질랜드</option>
                </select>
            </div>
            <div class="product">
                <select name="" id="product_box">
                    <option>제품선택</option>
                    <option>선식</option>
                    <option>빌지처리</option>
                    <option>선창클리닝</option>
                    <option>선박부품</option>
                    <option>선박수리</option>
                    <option>주부식</option>
                    <option>면세품</option>
                    <option>선용품</option>
                    <option>슬러지 양륙</option>
                    <option>기부속</option>
                    <option>청수</option>
                    <option>쓰레기, 폐유처리</option>
                    <option>선용금</option>
                    <option>SPRO계약</option>
                    <option>개인물품</option>
                    <option>세탁물</option>
                    <option>대리점 업무</option>
                    <option>기타</option>
                </select>
            </div>
            <input type="text" placeholder="검색어를 입력해주세요" class="search_box"><svg class="provision_glass"
                xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512">
                <path
                    d="M416 208c0 45.9-14.9 88.3-40 122.7L502.6 457.4c12.5 12.5 12.5 32.8 0 45.3s-32.8 12.5-45.3 0L330.7 376c-34.4 25.2-76.8 40-122.7 40C93.1 416 0 322.9 0 208S93.1 0 208 0S416 93.1 416 208zM208 352c79.5 0 144-64.5 144-144s-64.5-144-144-144S64 128.5 64 208s64.5 144 144 144z" />
            </svg>
            <button class="provision_search_btn">검색</button>
        </div>
        <ul class="bg_icon">
            <li class="company"><a href="#" class="company_icon">
                    <figure class="fig1"><img src="images/company.png" alt="업체조회">
                        <figcaption class="figcap1">업체조회</figcaption>
                    </figure>
                </a></li>
            <li class="check"><a href="#" class="check_icon">
                    <figure class="fig2"><img src="images/check.png" alt="배송조회">
                        <figcaption class="figcap2">배송조회</figcaption>
                    </figure>
                </a></li>
            <li class="reg"><a href="provision_reg.html" class="reg_icon">
                    <figure class="fig3"><img src="images/reg.png" alt="배송조회">
                        <figcaption class="figcap3">업체등록</figcaption>
                    </figure>
                </a></li>
            <li class="guide"><a href="#" class="guide_icon">
                    <figure class="fig4"><img src="images/guide.png" alt="이용안내">
                        <figcaption class="figcap4">이용안내</figcaption>
                    </figure>
                </a></li>
        </ul>
    </fieldset>
</form>
</section>
