<h2 class="vip_title">VIP 구인광고</h2>
<div class="vip_ad">
    <ul class="vip_box1" id="vip_box">
        <a href="#">
            <li class="vip_ad1">
                <div class="ad1_color">
                    <dl class="ad1_txt">
                        <dt>HMM</dt>
                        <dd class="ad1_desc">해상직원(PCTC/BULK/CNTR/VLCC 선대 경력)및 육상직원 모집</dd>
                        <dd class="day1">D-3</dd>
                    </dl>
                </div>
            </li>
        </a>
        <a href="#">
            <li class="vip_ad2">
                <div class="ad2_color">
                    <dl class="ad2_txt">
                        <dt>SK shipping</dt>
                        <dd class="ad2_desc">[SK해운] LNGC 프로젝트 신조감독 채용</dd>
                        <dd class="day2">D-7</dd>
                    </dl>
                </div>
            </li>
        </a>
        <a href="#">
            <li class="vip_ad3">
                <div class="ad3_color">
                    <dl class="ad3_txt">
                        <dt>고려해운</dt>
                        <dd class="ad3_desc">(주)고려해운 정규직 해상직원 채용공고</dd>
                        <dd class="day3">D-8</dd>
                    </dl>
                </div>
            </li>
        </a>
        <a href="#">
            <li class="vip_ad4">
                <div class="ad4_color">
                    <dl class="ad4_txt">
                        <dt>윌헴슨쉽매니지먼트코리아(주)</dt>
                        <dd class="ad4_desc">월급 10%인상 해상직 모집</dd>
                        <dd class="day4">D-5</dd>
                    </dl>
                </div>
            </li>
        </a>
        <a href="#">
            <li class="vip_ad5">
                <div class="ad5_color">
                    <dl class="ad5_txt">
                        <dt>현대LNG해운</dt>
                        <dd class="ad5_desc">현대LNG해운 경력직 해기사 상시모집(선종 변경 가능)</dd>
                        <dd class="day5">상시모집</dd>
                    </dl>
                </div>
            </li>
        </a>
        <a href="#">
            <li class="vip_ad6">
                <div class="ad6_color">
                    <dl class="ad6_txt">
                        <dt>SM Group 해운부문</dt>
                        <dd class="ad6_desc">[SM그룹 해운부문] BULK선 해상직원 채용 !!급여인상완료!!</dd>
                        <dd class="day6">상시모집</dd>
                    </dl>
                </div>
            </li>
        </a>
        <a href="#">
            <li class="vip_ad7">
                <div class="ad7_color">
                    <dl class="ad7_txt">
                        <dt>에이치라인해운(주)</dt>
                        <dd class="ad7_desc">에이치라인해운(주) PCTC선 공무감독 모집</dd>
                        <dd class="day7">D-10</dd>
                    </dl>
                </div>
            </li>
        </a>
        <a href="#">
            <li class="vip_ad8">
                <div class="ad8_color">
                    <dl class="ad8_txt">
                        <dt>POS SM</dt>
                        <dd class="ad8_desc">(팬오션) 선장, 기관장, 1항기사, 2항기사, 부원</dd>
                        <dd class="day8">상시모집</dd>
                    </dl>
                </div>
            </li>
        </a>
        <a href="#">
            <li class="vip_ad1">
                <div class="ad1_color">
                    <dl class="ad1_txt">
                        <dt>HMM</dt>
                        <dd class="ad1_desc">해상직원(PCTC/BULK/CNTR/VLCC 선대 경력)및 육상직원 모집</dd>
                        <dd class="day1">D-3</dd>
                    </dl>
                </div>
            </li>
        </a>
        <a href="#">
            <li class="vip_ad2">
                <div class="ad2_color">
                    <dl class="ad2_txt">
                        <dt>SK shipping</dt>
                        <dd class="ad2_desc">[SK해운] LNGC 프로젝트 신조감독 채용</dd>
                        <dd class="day2">D-7</dd>
                    </dl>
                </div>
            </li>
        </a>
        <a href="#">
            <li class="vip_ad3">
                <div class="ad3_color">
                    <dl class="ad3_txt">
                        <dt>고려해운</dt>
                        <dd class="ad3_desc">(주)고려해운 정규직 해상직원 채용공고</dd>
                        <dd class="day3">D-8</dd>
                    </dl>
                </div>
            </li>
        </a>
        <a href="#">
            <li class="vip_ad4">
                <div class="ad4_color">
                    <dl class="ad4_txt">
                        <dt>윌헴슨쉽매니지먼트코리아(주)</dt>
                        <dd class="ad4_desc">월급 10%인상 해상직 모집</dd>
                        <dd class="day4">D-5</dd>
                    </dl>
                </div>
            </li>
        </a>
        <a href="#">
            <li class="vip_ad1">
                <div class="ad1_color">
                    <dl class="ad1_txt">
                        <dt>HMM</dt>
                        <dd class="ad1_desc">해상직원(PCTC/BULK/CNTR/VLCC 선대 경력)및 육상직원 모집</dd>
                        <dd class="day1">D-3</dd>
                    </dl>
                </div>
            </li>
        </a>
        <a href="#">
            <li class="vip_ad2">
                <div class="ad2_color">
                    <dl class="ad2_txt">
                        <dt>SK shipping</dt>
                        <dd class="ad2_desc">[SK해운] LNGC 프로젝트 신조감독 채용</dd>
                        <dd class="day2">D-7</dd>
                    </dl>
                </div>
            </li>
        </a>
        <a href="#">
            <li class="vip_ad3">
                <div class="ad3_color">
                    <dl class="ad3_txt">
                        <dt>고려해운</dt>
                        <dd class="ad3_desc">(주)고려해운 정규직 해상직원 채용공고</dd>
                        <dd class="day3">D-8</dd>
                    </dl>
                </div>
            </li>
        </a>
        <a href="#">
            <li class="vip_ad4">
                <div class="ad4_color">
                    <dl class="ad4_txt">
                        <dt>윌헴슨쉽매니지먼트코리아(주)</dt>
                        <dd class="ad4_desc">월급 10%인상 해상직 모집</dd>
                        <dd class="day4">D-5</dd>
                    </dl>
                </div>
            </li>
        </a>
        <a href="#">
            <li class="vip_ad5">
                <div class="ad5_color">
                    <dl class="ad5_txt">
                        <dt>현대LNG해운</dt>
                        <dd class="ad5_desc">현대LNG해운 경력직 해기사 상시모집(선종 변경 가능)</dd>
                        <dd class="day5">상시모집</dd>
                    </dl>
                </div>
            </li>
        </a>
        <a href="#">
            <li class="vip_ad6">
                <div class="ad6_color">
                    <dl class="ad6_txt">
                        <dt>SM Group 해운부문</dt>
                        <dd class="ad6_desc">[SM그룹 해운부문] BULK선 해상직원 채용 !!급여인상완료!!</dd>
                        <dd class="day6">상시모집</dd>
                    </dl>
                </div>
            </li>
        </a>
        <a href="#">
            <li class="vip_ad7">
                <div class="ad7_color">
                    <dl class="ad7_txt">
                        <dt>에이치라인해운(주)</dt>
                        <dd class="ad7_desc">에이치라인해운(주) PCTC선 공무감독 모집</dd>
                        <dd class="day7">D-10</dd>
                    </dl>
                </div>
            </li>
        </a>
        <a href="#">
            <li class="vip_ad8">
                <div class="ad8_color">
                    <dl class="ad8_txt">
                        <dt>POS SM</dt>
                        <dd class="ad8_desc">(팬오션) 선장, 기관장, 1항기사, 2항기사, 부원</dd>
                        <dd class="day8">상시모집</dd>
                    </dl>
                </div>
            </li>
        </a>
        <a href="#">
            <li class="vip_ad1">
                <div class="ad1_color">
                    <dl class="ad1_txt">
                        <dt>HMM</dt>
                        <dd class="ad1_desc">해상직원(PCTC/BULK/CNTR/VLCC 선대 경력)및 육상직원 모집</dd>
                        <dd class="day1">D-3</dd>
                    </dl>
                </div>
            </li>
        </a>
        <a href="#">
            <li class="vip_ad2">
                <div class="ad2_color">
                    <dl class="ad2_txt">
                        <dt>SK shipping</dt>
                        <dd class="ad2_desc">[SK해운] LNGC 프로젝트 신조감독 채용</dd>
                        <dd class="day2">D-7</dd>
                    </dl>
                </div>
            </li>
        </a>
        <a href="#">
            <li class="vip_ad3">
                <div class="ad3_color">
                    <dl class="ad3_txt">
                        <dt>고려해운</dt>
                        <dd class="ad3_desc">(주)고려해운 정규직 해상직원 채용공고</dd>
                        <dd class="day3">D-8</dd>
                    </dl>
                </div>
            </li>
        </a>
        <a href="#">
            <li class="vip_ad4">
                <div class="ad4_color">
                    <dl class="ad4_txt">
                        <dt>윌헴슨쉽매니지먼트코리아(주)</dt>
                        <dd class="ad4_desc">월급 10%인상 해상직 모집</dd>
                        <dd class="day4">D-5</dd>
                    </dl>
                </div>
            </li>
        </a>
    </ul>
    <p class="vip_more">펼치기></p>
</div>