<section class="basic_ad">
    <h2>일반 구인광고</h2>
    <div class="ad">
        <a href="#">
            <dl class="ad1">
                <div class="ad1_bg">
                    <dt>바르질라코리아(주)</dt>
                    <dd class="dd">Propulsion and E&A Service Engineer 경력자 모집</dd>
                    <dd class="day">D-8</dd>
                </div>
            </dl>
        </a>
        <a href="#">
            <dl class="ad2">
                <div class="ad2_bg">
                    <dt>싱크로해운주식회사</dt>
                    <dd class="dd">[급구] VLCC 전 직급 모집 - 선장 급구 & [육상 직원] 안전기획팀...</dd>
                    <dd class="day">상시모집</dd>
                </div>
            </dl>
        </a>
        <a href="#">
            <dl class="ad3">
                <div class="ad3_bg">
                    <dt>Triad M</dt>
                    <dd class="dd">울산 SK T5 터미널 하역안전관리자 모집</dd>
                    <dd class="day">D-8</dd>
                </div>
            </dl>
        </a>
        <a href="#">
            <dl class="ad4">
                <div class="ad4_bg">
                    <dt>KTM Shipping</dt>
                    <dd class="dd">[OIL & CHEMICAL] 일항사 모집</dd>
                    <dd class="day">D-8</dd>
                </div>
            </dl>
        </a>
        <a href="#">
            <dl class="ad5">
                <div class="ad5_bg">
                    <dt>마린웍스 주식회사</dt>
                    <dd class="dd">스마트십, 사이버보안, 자율운항 선박 등 연구 개발 및 IT분야...</dd>
                    <dd class="day">D-8</dd>
                </div>
            </dl>
        </a>
        <a href="#">
            <dl class="ad6">
                <div class="ad6_bg">
                    <dt>(주)티제이에스엠</dt>
                    <dd class="dd">TANKER 선단 해상직원 모십니다.</dd>
                    <dd class="day">D-8</dd>
                </div>
            </dl>
        </a>
        <a href="#">
            <dl class="ad7">
                <div class="ad7_bg">
                    <dt>(주)한일고속</dt>
                    <dd class="dd">(주)한일고속 대형카페리여객선 공무감독 모집</dd>
                    <dd class="day">D-8</dd>
                </div>
            </dl>
        </a>
        <a href="#">
            <dl class="ad8">
                <div class="ad8_bg">
                    <dt>동진상선(주)</dt>
                    <dd class="dd">정기기항 컨테이너 기관사관(1,2,3기사)모십니다</dd>
                    <dd class="day">D-8</dd>
                </div>
            </dl>
        </a>
        <a href="#">
            <dl class="ad9">
                <div class="ad9_bg">
                    <dt>고려해운(주)</dt>
                    <dd class="dd">(주)고려해운 정규직 해상직원 채용 공고</dd>
                    <dd class="day">D-8</dd>
                </div>
            </dl>
        </a>
        <a href="#">
            <dl class="ad21">
                <div class="ad21_bg">
                    <dt>시도상선(주)</dt>
                    <dd class="dd">공무감독-시도상선(주)</dd>
                    <dd class="day">D-8</dd>
                </div>
            </dl>
        </a>
        <a href="#">
            <dl class="ad11">
                <div class="ad11_bg">
                    <dt>TOTAL</dt>
                    <dd class="dd">[TOTAL] 전 직급 사관 모집</dd>
                    <dd class="day">D-8</dd>
                </div>
            </dl>
        </a>
        <a href="#">
            <dl class="ad12">
                <div class="ad12_bg">
                    <dt>(주)KSS해운</dt>
                    <dd class="dd">[KSS해운] 대형 LPG(VLGC) 전 사관 직책 적극 채용 중</dd>
                    <dd class="day">D-8</dd>
                </div>
            </dl>
        </a>
        <a href="#">
            <dl class="ad13">
                <div class="ad13_bg">
                    <dt>(주)남해고속</dt>
                    <dd class="dd">국내 여객선 기관사, 3항사, 조리수 모집</dd>
                    <dd class="day">D-8</dd>
                </div>
            </dl>
        </a>
        <a href="#">
            <dl class="ad14">
                <div class="ad14_bg">
                    <dt>범진상운 주식회사</dt>
                    <dd class="dd">장금상선 선대 확충으로 인한 전직급 구인중!</dd>
                    <dd class="day">D-8</dd>
                </div>
            </dl>
        </a>
        <a href="#">
            <dl class="ad15">
                <div class="ad15_bg">
                    <dt>폴라리스쉬핑(주)</dt>
                    <dd class="dd">채용공고-1항사,1기사,2기사</dd>
                    <dd class="day">D-8</dd>
                </div>
            </dl>
        </a>
        <a href="#">
            <dl class="ad16">
                <div class="ad16_bg">
                    <dt>S-OIL</dt>
                    <dd class="dd">[S-OIL] 원유운반선 항무사 채용</dd>
                    <dd class="day">D-8</dd>
                </div>
            </dl>
        </a>
        <a href="#">
            <dl class="ad17">
                <div class="ad17_bg">
                    <dt>현대글로비스</dt>
                    <dd class="dd">2022년 현대 글로비스 유통/해운부문 경력직 채용</dd>
                    <dd class="day">D-8</dd>
                </div>
            </dl>
        </a>
        <a href="#">
            <dl class="ad22">
                <div class="ad22_bg">
                    <dt>디엘에스엠(주)</dt>
                    <dd class="dd">컨테이너 & 벌크 전사관 모집</dd>
                    <dd class="day">D-8</dd>
                </div>
            </dl>
        </a>
        <a href="#">
            <dl class="ad23">
                <div class="ad23_bg">
                    <dt>(주)오렌지씨큐리티</dt>
                    <dd class="dd">해사 사이버보안 컨설턴트 (항해/기관)</dd>
                    <dd class="day">D-8</dd>
                </div>
            </dl>
        </a>
        <a href="#">
            <dl class="ad20">
                <div class="ad20_bg">
                    <dt>(주)리앤쉽핑</dt>
                    <dd class="dd">리앤쉽핑-내항선 이등(삼등)항해사 모집</dd>
                    <dd class="day">D-8</dd>
                </div>
            </dl>
        </a>
        <a href="#">
            <dl class="ad1">
                <div class="ad1_bg">
                    <dt>바르질라코리아(주)</dt>
                    <dd class="dd">Propulsion and E&A Service Engineer 경력자 모집</dd>
                    <dd class="day">D-8</dd>
                </div>
            </dl>
        </a>
        <a href="#">
            <dl class="ad2">
                <div class="ad2_bg">
                    <dt>싱크로해운주식회사</dt>
                    <dd class="dd">[급구] VLCC 전 직급 모집 - 선장 급구 & [육상 직원] 안전기획팀...</dd>
                    <dd class="day">상시모집</dd>
                </div>
            </dl>
        </a>
        <a href="#">
            <dl class="ad3">
                <div class="ad3_bg">
                    <dt>Triad M</dt>
                    <dd class="dd">울산 SK T5 터미널 하역안전관리자 모집</dd>
                    <dd class="day">D-8</dd>
                </div>
            </dl>
        </a>
        <a href="#">
            <dl class="ad4">
                <div class="ad4_bg">
                    <dt>KTM Shipping</dt>
                    <dd class="dd">[OIL & CHEMICAL] 일항사 모집</dd>
                    <dd class="day">D-8</dd>
                </div>
            </dl>
        </a>
        <a href="#">
            <dl class="ad5">
                <div class="ad5_bg">
                    <dt>마린웍스 주식회사</dt>
                    <dd class="dd">스마트십, 사이버보안, 자율운항 선박 등 연구 개발 및 IT분야...</dd>
                    <dd class="day">D-8</dd>
                </div>
            </dl>
        </a>
        <a href="#">
            <dl class="ad6">
                <div class="ad6_bg">
                    <dt>(주)티제이에스엠</dt>
                    <dd class="dd">TANKER 선단 해상직원 모십니다.</dd>
                    <dd class="day">D-8</dd>
                </div>
            </dl>
        </a>
        <a href="#">
            <dl class="ad7">
                <div class="ad7_bg">
                    <dt>(주)한일고속</dt>
                    <dd class="dd">(주)한일고속 대형카페리여객선 공무감독 모집</dd>
                    <dd class="day">D-8</dd>
                </div>
            </dl>
        </a>
        <a href="#">
            <dl class="ad8">
                <div class="ad8_bg">
                    <dt>동진상선(주)</dt>
                    <dd class="dd">정기기항 컨테이너 기관사관(1,2,3기사)모십니다</dd>
                    <dd class="day">D-8</dd>
                </div>
            </dl>
        </a>
        <a href="#">
            <dl class="ad9">
                <div class="ad9_bg">
                    <dt>고려해운(주)</dt>
                    <dd class="dd">(주)고려해운 정규직 해상직원 채용 공고</dd>
                    <dd class="day">D-8</dd>
                </div>
            </dl>
        </a>
        <a href="#">
            <dl class="ad21">
                <div class="ad21_bg">
                    <dt>시도상선(주)</dt>
                    <dd class="dd">공무감독-시도상선(주)</dd>
                    <dd class="day">D-8</dd>
                </div>
            </dl>
        </a>
        <a href="#">
            <dl class="ad11">
                <div class="ad11_bg">
                    <dt>TOTAL</dt>
                    <dd class="dd">[TOTAL] 전 직급 사관 모집</dd>
                    <dd class="day">D-8</dd>
                </div>
            </dl>
        </a>
        <a href="#">
            <dl class="ad12">
                <div class="ad12_bg">
                    <dt>(주)KSS해운</dt>
                    <dd class="dd">[KSS해운] 대형 LPG(VLGC) 전 사관 직책 적극 채용 중</dd>
                    <dd class="day">D-8</dd>
                </div>
            </dl>
        </a>
        <a href="#">
            <dl class="ad13">
                <div class="ad13_bg">
                    <dt>(주)남해고속</dt>
                    <dd class="dd">국내 여객선 기관사, 3항사, 조리수 모집</dd>
                    <dd class="day">D-8</dd>
                </div>
            </dl>
        </a>
        <a href="#">
            <dl class="ad14">
                <div class="ad14_bg">
                    <dt>범진상운 주식회사</dt>
                    <dd class="dd">장금상선 선대 확충으로 인한 전직급 구인중!</dd>
                    <dd class="day">D-8</dd>
                </div>
            </dl>
        </a>
        <a href="#">
            <dl class="ad15">
                <div class="ad15_bg">
                    <dt>폴라리스쉬핑(주)</dt>
                    <dd class="dd">채용공고-1항사,1기사,2기사</dd>
                    <dd class="day">D-8</dd>
                </div>
            </dl>
        </a>
        <a href="#">
            <dl class="ad16">
                <div class="ad16_bg">
                    <dt>S-OIL</dt>
                    <dd class="dd">[S-OIL] 원유운반선 항무사 채용</dd>
                    <dd class="day">D-8</dd>
                </div>
            </dl>
        </a>
        <a href="#">
            <dl class="ad17">
                <div class="ad17_bg">
                    <dt>현대글로비스</dt>
                    <dd class="dd">2022년 현대 글로비스 유통/해운부문 경력직 채용</dd>
                    <dd class="day">D-8</dd>
                </div>
            </dl>
        </a>
        <a href="#">
            <dl class="ad22">
                <div class="ad22_bg">
                    <dt>디엘에스엠(주)</dt>
                    <dd class="dd">컨테이너 & 벌크 전사관 모집</dd>
                    <dd class="day">D-8</dd>
                </div>
            </dl>
        </a>
        <a href="#">
            <dl class="ad23">
                <div class="ad23_bg">
                    <dt>(주)오렌지씨큐리티</dt>
                    <dd class="dd">해사 사이버보안 컨설턴트 (항해/기관)</dd>
                    <dd class="day">D-8</dd>
                </div>
            </dl>
        </a>
        <a href="#">
            <dl class="ad20">
                <div class="ad20_bg">
                    <dt>(주)리앤쉽핑</dt>
                    <dd class="dd">리앤쉽핑-내항선 이등(삼등)항해사 모집</dd>
                    <dd class="day">D-8</dd>
                </div>
            </dl>
        </a>
        <a href="#">
            <dl class="ad1">
                <div class="ad1_bg">
                    <dt>바르질라코리아(주)</dt>
                    <dd class="dd">Propulsion and E&A Service Engineer 경력자 모집</dd>
                    <dd class="day">D-8</dd>
                </div>
            </dl>
        </a>
        <a href="#">
            <dl class="ad2">
                <div class="ad2_bg">
                    <dt>싱크로해운주식회사</dt>
                    <dd class="dd">[급구] VLCC 전 직급 모집 - 선장 급구 & [육상 직원] 안전기획팀...</dd>
                    <dd class="day">상시모집</dd>
                </div>
            </dl>
        </a>
        <a href="#">
            <dl class="ad3">
                <div class="ad3_bg">
                    <dt>Triad M</dt>
                    <dd class="dd">울산 SK T5 터미널 하역안전관리자 모집</dd>
                    <dd class="day">D-8</dd>
                </div>
            </dl>
        </a>
        <a href="#">
            <dl class="ad4">
                <div class="ad4_bg">
                    <dt>KTM Shipping</dt>
                    <dd class="dd">[OIL & CHEMICAL] 일항사 모집</dd>
                    <dd class="day">D-8</dd>
                </div>
            </dl>
        </a>
        <a href="#">
            <dl class="ad5">
                <div class="ad5_bg">
                    <dt>마린웍스 주식회사</dt>
                    <dd class="dd">스마트십, 사이버보안, 자율운항 선박 등 연구 개발 및 IT분야...</dd>
                    <dd class="day">D-8</dd>
                </div>
            </dl>
        </a>
        <a href="#">
            <dl class="ad6">
                <div class="ad6_bg">
                    <dt>(주)티제이에스엠</dt>
                    <dd class="dd">TANKER 선단 해상직원 모십니다.</dd>
                    <dd class="day">D-8</dd>
                </div>
            </dl>
        </a>
        <a href="#">
            <dl class="ad7">
                <div class="ad7_bg">
                    <dt>(주)한일고속</dt>
                    <dd class="dd">(주)한일고속 대형카페리여객선 공무감독 모집</dd>
                    <dd class="day">D-8</dd>
                </div>
            </dl>
        </a>
        <a href="#">
            <dl class="ad8">
                <div class="ad8_bg">
                    <dt>동진상선(주)</dt>
                    <dd class="dd">정기기항 컨테이너 기관사관(1,2,3기사)모십니다</dd>
                    <dd class="day">D-8</dd>
                </div>
            </dl>
        </a>
        <a href="#">
            <dl class="ad9">
                <div class="ad9_bg">
                    <dt>고려해운(주)</dt>
                    <dd class="dd">(주)고려해운 정규직 해상직원 채용 공고</dd>
                    <dd class="day">D-8</dd>
                </div>
            </dl>
        </a>
        <a href="#">
            <dl class="ad21">
                <div class="ad21_bg">
                    <dt>시도상선(주)</dt>
                    <dd class="dd">공무감독-시도상선(주)</dd>
                    <dd class="day">D-8</dd>
                </div>
            </dl>
        </a>
        <a href="#">
            <dl class="ad11">
                <div class="ad11_bg">
                    <dt>TOTAL</dt>
                    <dd class="dd">[TOTAL] 전 직급 사관 모집</dd>
                    <dd class="day">D-8</dd>
                </div>
            </dl>
        </a>
        <a href="#">
            <dl class="ad12">
                <div class="ad12_bg">
                    <dt>(주)KSS해운</dt>
                    <dd class="dd">[KSS해운] 대형 LPG(VLGC) 전 사관 직책 적극 채용 중</dd>
                    <dd class="day">D-8</dd>
                </div>
            </dl>
        </a>
        <a href="#">
            <dl class="ad13">
                <div class="ad13_bg">
                    <dt>(주)남해고속</dt>
                    <dd class="dd">국내 여객선 기관사, 3항사, 조리수 모집</dd>
                    <dd class="day">D-8</dd>
                </div>
            </dl>
        </a>
        <a href="#">
            <dl class="ad14">
                <div class="ad14_bg">
                    <dt>범진상운 주식회사</dt>
                    <dd class="dd">장금상선 선대 확충으로 인한 전직급 구인중!</dd>
                    <dd class="day">D-8</dd>
                </div>
            </dl>
        </a>
        <a href="#">
            <dl class="ad15">
                <div class="ad15_bg">
                    <dt>폴라리스쉬핑(주)</dt>
                    <dd class="dd">채용공고-1항사,1기사,2기사</dd>
                    <dd class="day">D-8</dd>
                </div>
            </dl>
        </a>
        <a href="#">
            <dl class="ad16">
                <div class="ad16_bg">
                    <dt>S-OIL</dt>
                    <dd class="dd">[S-OIL] 원유운반선 항무사 채용</dd>
                    <dd class="day">D-8</dd>
                </div>
            </dl>
        </a>
        <a href="#">
            <dl class="ad17">
                <div class="ad17_bg">
                    <dt>현대글로비스</dt>
                    <dd class="dd">2022년 현대 글로비스 유통/해운부문 경력직 채용</dd>
                    <dd class="day">D-8</dd>
                </div>
            </dl>
        </a>
        <a href="#">
            <dl class="ad22">
                <div class="ad22_bg">
                    <dt>디엘에스엠(주)</dt>
                    <dd class="dd">컨테이너 & 벌크 전사관 모집</dd>
                    <dd class="day">D-8</dd>
                </div>
            </dl>
        </a>
        <a href="#">
            <dl class="ad23">
                <div class="ad23_bg">
                    <dt>(주)오렌지씨큐리티</dt>
                    <dd class="dd">해사 사이버보안 컨설턴트 (항해/기관)</dd>
                    <dd class="day">D-8</dd>
                </div>
            </dl>
        </a>
        <a href="#">
            <dl class="ad20">
                <div class="ad20_bg">
                    <dt>(주)리앤쉽핑</dt>
                    <dd class="dd">리앤쉽핑-내항선 이등(삼등)항해사 모집</dd>
                    <dd class="day">D-8</dd>
                </div>
            </dl>
        </a>
    </div>
    <p class="ad_more">펼치기></p>
</section>