<footer>
        <div class="footer_wrap">
            <h2 class="footer_logo">seanet</h2>
            <h3 class="hide">회사약관</h3>
            <ul class="footer_menu">
                <li class="fnb1"><a href="#">회사소개</a></li>
                <li class="fnb2"><a href="#">찾아오시는 길</a></li>
                <li class="fnb3"><a href="#">회원약관</a></li>
                <li class="fnb4"><a href="#">개인정보처리방침</a></li>
                <li class="fnb5"><a href="#">제휴문의</a></li>
            </ul>
            <div class="footer_info">
                <p>대표자:전헤아림</p>
                <address>주소: 서울시 종로구 삼봉로 81, 1015호</address>
                <p>사업자등록번호 : 875-88-01605 | 직업정보제공사업 : 서울청 제 2022-8호 | 통신판매업신고 : 제 2020-서울종로-2492호</p>
                <p>문의 : info@deepcircle.net | 전화 : 02-538-5986 | 팩스 : 02-318-0261</p>
                <p>COPYRIGHT DEEPCIRCLE CO.,LTD ALL RIGHTS RESERVED. SINCE 1998.</p>
            </div>
        </div>
    </footer>